Remove mention creation state machine v1 in HKW library - Part 1
linkedin/Hakawai pull request #228
Opened 2020-12-29 14:45 UTC by aniyati

Remove mention creation state machine v1 in HKW library - Part 1

- Removed all use cases of `HKWMentionsCreationStateMachineV1` and deleted file `HKWMentionsCreationStateMachineV1`
- Moved all protocol methods/properties to `HKWMentionsCreationStateMachineV2` and removed protocol `HKWMentionsCreationStateMachine`

**Testing:**
- Test video added on https://drive.google.com/drive/u/0/folders/1tT6cmGjjUunzHc0Erx70GH5LI02cyUWw

2021-01-05 21:58 UTC, li-jychen approved these changes
just to confirm, in the next PR you will remove the v2 suffix in the files right?

2021-01-28 12:48 UTC, aniyati commented
> just to confirm, in the next PR you will remove the v2 suffix in the files right?

Yes next PR we will remove the v2 files

2021-01-28 19:23 UTC, bkoatz requested changes

2021-01-28 19:23 UTC, bkoatz commented on Hakawai/Mentions/HKWMentionsPluginV1.m
>  #import "_HKWMentionsCreationStateMachineV2.h"
can we remove the V2 from the name?

2021-01-29 16:59 UTC, bkoatz approved these changes

2021-01-29 16:59 UTC, merged