Remove mention creation state machine v1 in HKW library - Part 2
linkedin/Hakawai pull request #229
Opened 2021-02-01 10:46 UTC by aniyati

- Renamed file `HKWMentionsCreationStateMachine` to `HKWMentionsCreationStateMachineProtocol`.
- Renamed file `HKWMentionsCreationStateMachineV2` to `HKWMentionsCreationStateMachine`.

2021-02-02 04:31 UTC, bkoatz requested changes

2021-02-02 04:31 UTC, bkoatz commented on Hakawai/Mentions/_HKWMentionsCreationStateMachine.h
> +
extra space

2021-02-02 04:31 UTC, bkoatz commented on Hakawai/Mentions/HKWMentionsCreationStateMachineProtocol.h
> +@protocol HKWMentionsCreationStateMachineProtocol <HKWMentionsDefaultChooserViewDelegate, HKWMentionsCustomChooserViewDelegate>
i think this can be called HKWMentionsCreationStateMachineDelegate, instead. which would be cleared

2021-02-02 04:32 UTC, bkoatz commented
also the tests are failing - have u run tests locally to make sure they're passing?

2021-02-02 04:38 UTC, aniyati commented
> also the tests are failing - have u run tests locally to make sure they're passing?

We ran the `HakawaiTest` target locally. All the test passed locally. We're not sure what exactly is causing `xcodebuild failed`. We're investigating further.

2021-02-02 18:39 UTC, bkoatz requested changes
Please check out tests and let's get this not to be failing :)

2021-02-02 18:39 UTC, bkoatz commented on Hakawai/Mentions/HKWMentionsCreationStateMachineProtocol.h
> +@protocol HKWMentionsCreationStateMachineProtocol <HKWMentionsDefaultChooserViewDelegate, HKWMentionsCustomChooserViewDelegate>
i think this class + file needs to be renamed

2021-02-04 19:58 UTC, bkoatz approved these changes

2021-02-04 19:59 UTC, merged